### PR TITLE
Build changes

### PR DESCRIPTION
**Pull request by jamiebuilds**
WIP

### CODE REVIEW

**Comment by jamiebuilds** [comment]
oh, I was gonna keep going later

**Comment by jamesplease** [comment]
:speak_no_evil:

**Comment by jridgewell** [comment]
:stuck_out_tongue:

**Comment by jamesplease** [comment]
:skull:

**Comment by jamiebuilds** [comment]
rebeccablack-1414024054

**Comment by jridgewell** [comment]
@jmeas

**Pull request merged**
